wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1644396878
    t:
      1:
      - 3
      2:
      - 3
      3:
      - 3
      - 8
      - 16
      4: 3.7.9
      5: 0.12.10
      8:
      - 3
      - 5
images_per_GPU:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.001
model_id:
  desc: null
  value: models\dimo20220209T0954
steps_per_epoch:
  desc: null
  value: 1000
subsets:
  desc: null
  value:
  - sim_jaigo_real_light_real_pose
training_images:
  desc: null
  value: 21
